# **EXPRIMENT 1:**
Loading and merging data sets using UCI ML repository.

*   Loading
*   Merging
*   Flitering
*   Sampeling

import statements

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

LOADING FILES INTO GOOGLE COLLAB

In [6]:
df1 = pd.read_csv('student3.csv');
df2 = pd.read_csv("Student_5.csv")
df1
df2

    roll     name class  marks     age
0      1     anil    TE   56.77   22.0
1      2     amit    TE   59.77   21.0
2      3   aniket    BE   76.88   19.0
3      4  ajinkya    TE   69.66   20.0
4      5     asha    TE   63.28    NaN
5      6   ayesha    BE     NaN   20.0
6      7     amar    BE   65.34   19.0
7      7     amar    BE   65.34   19.0
8      8    Amita    be  168.33   23.0
9      9     amol    TE   56.75   20.0
10    10    anmol    BE   78.66    NaN
11    11   surbhi    TE     NaN   23.0
12    12    Sujay    TE   74.12   22.0
13    13  subhash    be   88.45  121.0
14    14   sachin   NaN   59.33   21.0
15    15  shalini    TE   63.45   20.0

MERGING BOTH DATASETS

In [9]:
merged = pd.merge(df1, df2, on='age')
merged

    roll_x   name_x class_x  marks _x   age  roll_y   name_y class_y  marks _y
0        1     anil      TE     56.77  22.0       1     anil      TE     56.77
1        1     anil      TE     56.77  22.0      12    Sujay      TE     74.12
2       12    Sujay      TE     74.12  22.0       1     anil      TE     56.77
3       12    Sujay      TE     74.12  22.0      12    Sujay      TE     74.12
4        2     amit      TE     59.77  21.0       2     amit      TE     59.77
5        2     amit      TE     59.77  21.0      14   sachin     NaN     59.33
6       13  subhash      be     88.45  21.0       2     amit      TE     59.77
7       13  subhash      be     88.45  21.0      14   sachin     NaN     59.33
8       14   sachin     NaN     59.33  21.0       2     amit      TE     59.77
9       14   sachin     NaN     59.33  21.0      14   sachin     NaN     59.33
10       3   aniket      BE     76.88  19.0       3   aniket      BE     76.88
11       3   aniket      BE     76.88  19.0       7     amar      BE     65.34
12       3   aniket      BE     76.88  19.0       7     amar      BE     65.34
13       7     amar      BE     65.34  19.0       3   aniket      BE     76.88
14       7     amar      BE     65.34  19.0       7     amar      BE     65.34
15       7     amar      BE     65.34  19.0       7     amar      BE     65.34
16       4  ajinkya      TE     69.66  20.0       4  ajinkya      TE     69.66
17       4  ajinkya      TE     69.66  20.0       6   ayesha      BE       NaN
18       4  ajinkya      TE     69.66  20.0       9     amol      TE     56.75
19       4  ajinkya      TE     69.66  20.0      15  shalini      TE     63.45
20       6   ayesha      BE       NaN  20.0       4  ajinkya      TE     69.66
21       6   ayesha      BE       NaN  20.0       6   ayesha      BE       NaN
22       6   ayesha      BE       NaN  20.0       9     amol      TE     56.75
23       6   ayesha      BE       NaN  20.0      15  shalini      TE     63.45
24       9     amol      TE     56.75  20.0       4  ajinkya      TE     69.66
25       9     amol      TE     56.75  20.0       6   ayesha      BE       NaN
26       9     amol      TE     56.75  20.0       9     amol      TE     56.75
27       9     amol      TE     56.75  20.0      15  shalini      TE     63.45
28       9     amol      TE     56.75  20.0       4  ajinkya      TE     69.66
29       9     amol      TE     56.75  20.0       6   ayesha      BE       NaN
30       9     amol      TE     56.75  20.0       9     amol      TE     56.75
31       9     amol      TE     56.75  20.0      15  shalini      TE     63.45
32      15  shalini      TE     63.45  20.0       4  ajinkya      TE     69.66
33      15  shalini      TE     63.45  20.0       6   ayesha      BE       NaN
34      15  shalini      TE     63.45  20.0       9     amol      TE     56.75
35      15  shalini      TE     63.45  20.0      15  shalini      TE     63.45
36       5     asha      TE     63.28   NaN       5     asha      TE     63.28
37       5     asha      TE     63.28   NaN      10    anmol      BE     78.66
38      10    anmol      BE     78.66   NaN       5     asha      TE     63.28
39      10    anmol      BE     78.66   NaN      10    anmol      BE     78.66
40       8    Amita      be     68.33  23.0       8    Amita      be    168.33
41       8    Amita      be     68.33  23.0      11   surbhi      TE       NaN
42      11   surbhi      TE       NaN  23.0       8    Amita      be    168.33
43      11   surbhi      TE       NaN  23.0      11   surbhi      TE       NaN

FILTERING OF DATA ON TWO PARAMETERS

In [11]:
merged.filter(["name_x","name_y"])

     name_x   name_y
0      anil     anil
1      anil    Sujay
2     Sujay     anil
3     Sujay    Sujay
4      amit     amit
5      amit   sachin
6   subhash     amit
7   subhash   sachin
8    sachin     amit
9    sachin   sachin
10   aniket   aniket
11   aniket     amar
12   aniket     amar
13     amar   aniket
14     amar     amar
15     amar     amar
16  ajinkya  ajinkya
17  ajinkya   ayesha
18  ajinkya     amol
19  ajinkya  shalini
20   ayesha  ajinkya
21   ayesha   ayesha
22   ayesha     amol
23   ayesha  shalini
24     amol  ajinkya
25     amol   ayesha
26     amol     amol
27     amol  shalini
28     amol  ajinkya
29     amol   ayesha
30     amol     amol
31     amol  shalini
32  shalini  ajinkya
33  shalini   ayesha
34  shalini     amol
35  shalini  shalini
36     asha     asha
37     asha    anmol
38    anmol     asha
39    anmol    anmol
40    Amita    Amita
41    Amita   surbhi
42   surbhi    Amita
43   surbhi   surbhi

SAMPLING OF DATASETS

In [16]:
merged.sample(frac =.69)

    roll_x   name_x class_x  marks _x   age  roll_y   name_y class_y  marks _y
9       14   sachin     NaN     59.33  21.0      14   sachin     NaN     59.33
1        1     anil      TE     56.77  22.0      12    Sujay      TE     74.12
29       9     amol      TE     56.75  20.0       6   ayesha      BE       NaN
8       14   sachin     NaN     59.33  21.0       2     amit      TE     59.77
41       8    Amita      be     68.33  23.0      11   surbhi      TE       NaN
42      11   surbhi      TE       NaN  23.0       8    Amita      be    168.33
37       5     asha      TE     63.28   NaN      10    anmol      BE     78.66
21       6   ayesha      BE       NaN  20.0       6   ayesha      BE       NaN
11       3   aniket      BE     76.88  19.0       7     amar      BE     65.34
6       13  subhash      be     88.45  21.0       2     amit      TE     59.77
39      10    anmol      BE     78.66   NaN      10    anmol      BE     78.66
7       13  subhash      be     88.45  21.0      14   sachin     NaN     59.33
2       12    Sujay      TE     74.12  22.0       1     anil      TE     56.77
13       7     amar      BE     65.34  19.0       3   aniket      BE     76.88
12       3   aniket      BE     76.88  19.0       7     amar      BE     65.34
17       4  ajinkya      TE     69.66  20.0       6   ayesha      BE       NaN
28       9     amol      TE     56.75  20.0       4  ajinkya      TE     69.66
23       6   ayesha      BE       NaN  20.0      15  shalini      TE     63.45
43      11   surbhi      TE       NaN  23.0      11   surbhi      TE       NaN
26       9     amol      TE     56.75  20.0       9     amol      TE     56.75
38      10    anmol      BE     78.66   NaN       5     asha      TE     63.28
30       9     amol      TE     56.75  20.0       9     amol      TE     56.75
4        2     amit      TE     59.77  21.0       2     amit      TE     59.77
31       9     amol      TE     56.75  20.0      15  shalini      TE     63.45
15       7     amar      BE     65.34  19.0       7     amar      BE     65.34
10       3   aniket      BE     76.88  19.0       3   aniket      BE     76.88
19       4  ajinkya      TE     69.66  20.0      15  shalini      TE     63.45
14       7     amar      BE     65.34  19.0       7     amar      BE     65.34
36       5     asha      TE     63.28   NaN       5     asha      TE     63.28
20       6   ayesha      BE       NaN  20.0       4  ajinkya      TE     69.66

**EXPERIMENT 2**
---
*   Data Preprocessing-Cleaning the data set using data set obtained from UCI ML repository

Importing essential libraries

In [17]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [19]:
df = pd.read_csv('student3.csv')
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

Data Inspection

In [21]:
df.head()
df.info()
df.describe()
df.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 768.0+ bytes

     roll   name  class  marks     age
0   False  False  False   False  False
1   False  False  False   False  False
2   False  False  False   False  False
3   False  False  False   False  False
4   False  False  False   False   True
5   False  False  False    True  False
6   False  False  False   False  False
7   False  False  False   False  False
8   False  False  False   False  False
9   False  False  False   False  False
10  False  False  False   False   True
11  False  False  False    True  False
12  False  False  False   False  False
13  False  False  False   False  False
14  False  False   True   False  False
15  False  False  False   False  False

In [23]:
df.dropna()

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
15    15  shalini    TE   63.45  20.0

Handling Missing values

In [25]:
df['marks '].fillna(df['marks '].median())

0     56.770
1     59.770
2     76.880
3     69.660
4     63.280
5     64.395
6     65.340
7     68.330
8     56.750
9     56.750
10    78.660
11    64.395
12    74.120
13    88.450
14    59.330
15    63.450
Name: marks , dtype: float64

In [27]:
df['age'].fillna(df['age'].mode()[0])

0     22.0
1     21.0
2     19.0
3     20.0
4     20.0
5     20.0
6     19.0
7     23.0
8     20.0
9     20.0
10    20.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [28]:
df.dropna()

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
15    15  shalini    TE   63.45  20.0

Transforming Data

In [30]:
df = pd.read_csv('Social_Network_Ads.csv')
x = df[['Age','EstimatedSalary']]
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[0.02380952, 0.02962963],
       [0.4047619 , 0.03703704],
       [0.19047619, 0.20740741],
       [0.21428571, 0.31111111],
       [0.02380952, 0.45185185],
       [0.21428571, 0.31851852],
       [0.21428571, 0.51111111],
       [0.33333333, 1.        ],
       [0.16666667, 0.13333333],
       [0.4047619 , 0.37037037],
       [0.19047619, 0.48148148],
       [0.19047619, 0.27407407],
       [0.04761905, 0.52592593],
       [0.33333333, 0.02222222],
       [0.        , 0.4962963 ],
       [0.26190476, 0.48148148],
       [0.69047619, 0.07407407],
       [0.64285714, 0.08148148],
       [0.66666667, 0.0962963 ],
       [0.71428571, 0.1037037 ],
       [0.64285714, 0.05185185],
       [0.69047619, 0.25185185],
       [0.71428571, 0.19259259],
       [0.64285714, 0.05185185],
       [0.66666667, 0.05925926],
       [0.69047619, 0.03703704],
       [0.73809524, 0.0962963 ],
       [0.69047619, 0.11111111],
       [0.26190476, 0.20740741],
       [0.30952381, 0.02222222],
       [0.30952381, 0.43703704],
       [0.21428571, 0.9037037 ],
       [0.07142857, 0.00740741],
       [0.23809524, 0.21481481],
       [0.21428571, 0.55555556],
       [0.4047619 , 0.08888889],
       [0.35714286, 0.0962963 ],
       [0.28571429, 0.25185185],
       [0.19047619, 0.42222222],
       [0.21428571, 0.11851852],
       [0.21428571, 0.01481481],
       [0.35714286, 0.26666667],
       [0.4047619 , 0.68888889],
       [0.28571429, 0.        ],
       [0.23809524, 0.51111111],
       [0.11904762, 0.03703704],
       [0.16666667, 0.47407407],
       [0.21428571, 0.28888889],
       [0.28571429, 0.88888889],
       [0.30952381, 0.54814815],
       [0.14285714, 0.12592593],
       [0.        , 0.21481481],
       [0.26190476, 0.5037037 ],
       [0.4047619 , 0.05925926],
       [0.21428571, 0.31851852],
       [0.14285714, 0.2962963 ],
       [0.11904762, 0.24444444],
       [0.23809524, 0.47407407],
       [0.0952381 , 0.02222222],
       [0.33333333, 0.75555556],
       [0.21428571, 0.03703704],
       [0.16666667, 0.53333333],
       [0.11904762, 0.37777778],
       [0.33333333, 0.77777778],
       [0.97619048, 0.5037037 ],
       [0.14285714, 0.31851852],
       [0.14285714, 0.02962963],
       [0.11904762, 0.4962963 ],
       [0.0952381 , 0.35555556],
       [0.30952381, 0.39259259],
       [0.16666667, 0.48148148],
       [0.14285714, 0.08888889],
       [0.04761905, 0.05925926],
       [0.35714286, 0.72592593],
       [0.33333333, 0.02222222],
       [0.38095238, 0.71851852],
       [0.        , 0.27407407],
       [0.0952381 , 0.08888889],
       [0.23809524, 0.53333333],
       [0.19047619, 0.01481481],
       [0.28571429, 0.48148148],
       [0.5       , 0.2       ],
       [0.04761905, 0.25185185],
       [0.4047619 , 0.54074074],
       [0.28571429, 0.34814815],
       [0.30952381, 0.76296296],
       [0.14285714, 0.2962963 ],
       [0.23809524, 0.51851852],
       [0.19047619, 0.48888889],
       [0.4047619 , 0.25925926],
       [0.0952381 , 0.48888889],
       [0.28571429, 0.74814815],
       [0.19047619, 0.        ],
       [0.26190476, 0.0962963 ],
       [0.26190476, 0.5037037 ],
       [0.4047619 , 0.21481481],
       [0.4047619 , 0.07407407],
       [0.23809524, 0.8       ],
       [0.4047619 , 0.42962963],
       [0.23809524, 0.16296296],
       [0.21428571, 0.54074074],
       [0.23809524, 0.32592593],
       [0.33333333, 0.52592593],
       [0.35714286, 0.99259259],
       [0.02380952, 0.04444444],
       [0.07142857, 0.42222222],
       [0.19047619, 0.14814815],
       [0.21428571, 0.54814815],
       [0.19047619, 0.52592593],
       [0.47619048, 0.48148148],
       [0.5       , 0.41481481],
       [0.45238095, 0.41481481],
       [0.47619048, 0.34074074],
       [0.45238095, 0.2962963 ],
       [0.57142857, 0.48148148],
       [0.52380952, 0.31111111],
       [0.4047619 , 0.44444444],
       [0.42857143, 0.27407407],
       [0.52380952, 0.32592593],
       [0.54761905, 0.32592593],
       [0.42857143, 0.44444444],
       [0.45238095, 0.42222222],
       [0.52380952, 0.44444444],
       [0.4047619 , 0.28148148],
       [0.54761905, 0.26666667],
       [0.5       , 0.34074074],
       [0.57142857, 0.37037037],
       [0.19047619, 0.12592593],
       [0.28571429, 0.01481481],
       [0.19047619, 0.51111111],
       [0.30952381, 0.31851852],
       [0.35714286, 0.11851852],
       [0.28571429, 0.53333333],
       [0.07142857, 0.39259259],
       [0.23809524, 0.2962963 ],
       [0.11904762, 0.35555556],
       [0.04761905, 0.4962963 ],
       [0.28571429, 0.68148148],
       [0.23809524, 0.32592593],
       [0.02380952, 0.07407407],
       [0.02380952, 0.51851852],
       [0.        , 0.39259259],
       [0.4047619 , 0.32592593],
       [0.28571429, 0.54814815],
       [0.38095238, 0.07407407],
       [0.14285714, 0.54814815],
       [0.21428571, 0.6       ],
       [0.54761905, 0.11111111],
       [0.26190476, 0.34074074],
       [0.04761905, 0.43703704],
       [0.19047619, 0.        ],
       [0.54761905, 0.22222222],
       [0.30952381, 0.45185185],
       [0.42857143, 0.25925926],
       [0.52380952, 0.23703704],
       [0.30952381, 0.        ],
       [0.66666667, 0.32592593],
       [0.26190476, 0.44444444],
       [0.19047619, 0.11111111],
       [0.33333333, 0.88888889],
       [0.33333333, 0.62962963],
       [0.16666667, 0.55555556],
       [0.45238095, 0.13333333],
       [0.4047619 , 0.17037037],
       [0.35714286, 0.4       ],
       [0.        , 0.52592593],
       [0.0952381 , 0.2962963 ],
       [0.4047619 , 0.41481481],
       [0.26190476, 0.98518519],
       [0.26190476, 0.23703704],
       [0.07142857, 0.54074074],
       [0.38095238, 0.74074074],
       [0.19047619, 0.76296296],
       [0.38095238, 0.20740741],
       [0.38095238, 0.42222222],
       [0.11904762, 0.0962963 ],
       [0.4047619 , 0.23703704],
       [0.16666667, 0.05185185],
       [0.14285714, 0.05925926],
       [0.30952381, 0.14074074],
       [0.19047619, 0.00740741],
       [0.30952381, 0.41481481],
       [0.33333333, 0.75555556],
       [0.35714286, 0.20740741],
       [0.35714286, 0.33333333],
       [0.30952381, 0.37777778],
       [0.04761905, 0.4962963 ],
       [0.35714286, 0.19259259],
       [0.4047619 , 0.42222222],
       [0.23809524, 0.12592593],
       [0.14285714, 0.51111111],
       [0.02380952, 0.08148148],
       [0.26190476, 0.20740741],
       [0.02380952, 0.40740741],
       [0.23809524, 0.54814815],
       [0.38095238, 0.20740741],
       [0.28571429, 0.47407407],
       [0.04761905, 0.15555556],
       [0.19047619, 0.48148148],
       [0.4047619 , 0.05185185],
       [0.4047619 , 0.17777778],
       [0.73809524, 0.43703704],
       [0.5       , 0.88148148],
       [0.54761905, 0.41481481],
       [0.95238095, 0.63703704],
       [0.69047619, 0.23703704],
       [0.88095238, 0.85185185],
       [0.80952381, 0.73333333],
       [0.52380952, 0.94074074],
       [0.66666667, 0.05185185],
       [0.71428571, 0.6       ],
       [0.80952381, 1.        ],
       [0.97619048, 0.2       ],
       [0.4047619 , 0.31851852],
       [0.69047619, 0.20740741],
       [1.        , 0.68888889],
       [0.73809524, 0.37037037],
       [0.52380952, 0.46666667],
       [0.66666667, 0.6       ],
       [0.97619048, 0.94814815],
       [0.54761905, 0.48148148],
       [0.4047619 , 0.56296296],
       [0.45238095, 0.95555556],
       [1.        , 0.64444444],
       [0.4047619 , 0.33333333],
       [0.45238095, 0.28148148],
       [0.42857143, 0.82222222],
       [0.9047619 , 0.87407407],
       [0.52380952, 0.42222222],
       [0.57142857, 0.48148148],
       [0.4047619 , 0.97777778],
       [0.5       , 0.2       ],
       [0.52380952, 0.68148148],
       [0.73809524, 0.52592593],
       [0.47619048, 0.71851852],
       [0.66666667, 0.47407407],
       [0.52380952, 0.31111111],
       [0.45238095, 0.48148148],
       [0.66666667, 0.4962963 ],
       [0.83333333, 0.94814815],
       [0.57142857, 0.99259259],
       [0.47619048, 0.32592593],
       [0.76190476, 0.54074074],
       [0.9047619 , 0.65925926],
       [0.54761905, 0.42222222],
       [0.78571429, 0.97037037],
       [0.4047619 , 0.25925926],
       [0.92857143, 0.79259259],
       [0.54761905, 0.27407407],
       [0.4047619 , 0.60740741],
       [0.61904762, 0.17777778],
       [0.45238095, 0.27407407],
       [0.71428571, 0.88148148],
       [0.45238095, 0.97037037],
       [0.76190476, 0.21481481],
       [0.80952381, 0.55555556],
       [0.54761905, 0.42222222],
       [0.52380952, 0.31111111],
       [0.95238095, 0.59259259],
       [0.64285714, 0.85925926],
       [0.4047619 , 0.45925926],
       [0.42857143, 0.95555556],
       [0.88095238, 0.81481481],
       [0.4047619 , 0.42222222],
       [0.71428571, 0.55555556],
       [0.57142857, 0.68888889],
       [0.52380952, 0.44444444],
       [0.45238095, 0.43703704],
       [0.69047619, 0.95555556],
       [0.52380952, 0.34074074],
       [0.5952381 , 0.87407407],
       [0.97619048, 0.45185185],
       [1.        , 0.2       ],
       [0.5       , 0.67407407],
       [0.92857143, 0.08148148],
       [0.92857143, 0.43703704],
       [0.47619048, 0.41481481],
       [0.73809524, 0.54074074],
       [0.80952381, 0.17037037],
       [0.76190476, 0.15555556],
       [0.97619048, 0.54074074],
       [0.4047619 , 0.34074074],
       [0.45238095, 0.40740741],
       [0.80952381, 0.04444444],
       [0.71428571, 0.93333333],
       [0.45238095, 0.57777778],
       [0.45238095, 0.34814815],
       [0.71428571, 0.91111111],
       [0.54761905, 0.47407407],
       [0.45238095, 0.46666667],
       [0.5       , 0.88148148],
       [0.73809524, 0.54814815],
       [0.88095238, 0.17777778],
       [0.45238095, 0.45925926],
       [0.4047619 , 0.31111111],
       [0.42857143, 0.35555556],
       [0.57142857, 0.42962963],
       [0.5952381 , 0.71851852],
       [0.64285714, 0.47407407],
       [0.66666667, 0.75555556],
       [0.95238095, 0.17037037],
       [0.71428571, 0.43703704],
       [0.45238095, 0.9037037 ],
       [0.45238095, 0.47407407],
       [0.52380952, 0.33333333],
       [0.57142857, 0.28888889],
       [0.78571429, 0.88148148],
       [0.69047619, 0.72592593],
       [0.42857143, 0.81481481],
       [0.47619048, 0.25925926],
       [0.57142857, 0.40740741],
       [0.5       , 0.6       ],
       [0.47619048, 0.25925926],
       [0.73809524, 0.93333333],
       [0.5       , 0.47407407],
       [0.5       , 0.44444444],
       [0.85714286, 0.65925926],
       [0.4047619 , 0.2962963 ],
       [0.64285714, 0.12592593],
       [0.42857143, 0.33333333],
       [0.80952381, 0.91111111],
       [0.83333333, 0.4962963 ],
       [0.54761905, 0.27407407],
       [0.71428571, 0.11111111],
       [0.71428571, 0.85925926],
       [0.54761905, 0.33333333],
       [0.54761905, 0.42222222],
       [0.57142857, 0.44444444],
       [0.42857143, 0.76296296],
       [0.69047619, 0.68148148],
       [0.47619048, 0.26666667],
       [0.71428571, 0.77037037],
       [0.57142857, 0.37037037],
       [0.52380952, 0.37037037],
       [0.92857143, 0.33333333],
       [0.42857143, 0.28888889],
       [0.95238095, 0.95555556],
       [0.4047619 , 0.47407407],
       [0.47619048, 0.2962963 ],
       [0.5       , 0.79259259],
       [0.83333333, 0.65925926],
       [0.4047619 , 0.44444444],
       [0.47619048, 0.37037037],
       [0.69047619, 0.26666667],
       [0.69047619, 0.66666667],
       [0.54761905, 0.35555556],
       [0.83333333, 0.42222222],
       [0.85714286, 0.68888889],
       [0.5       , 0.45925926],
       [0.47619048, 0.34074074],
       [0.47619048, 0.72592593],
       [0.45238095, 0.44444444],
       [0.57142857, 0.55555556],
       [0.45238095, 0.31111111],
       [0.42857143, 0.62222222],
       [1.        , 0.14074074],
       [0.85714286, 0.40740741],
       [0.54761905, 0.42222222],
       [0.52380952, 0.41481481],
       [0.57142857, 0.28888889],
       [0.5952381 , 0.84444444],
       [0.83333333, 0.14074074],
       [0.69047619, 0.25925926],
       [0.57142857, 0.47407407],
       [0.57142857, 0.65925926],
       [0.97619048, 0.1037037 ],
       [0.95238095, 0.23703704],
       [0.66666667, 0.54074074],
       [0.47619048, 0.41481481],
       [0.85714286, 0.08148148],
       [1.        , 0.22962963],
       [1.        , 0.5037037 ],
       [0.5       , 0.42962963],
       [0.97619048, 0.85185185],
       [0.45238095, 0.48148148],
       [0.66666667, 0.12592593],
       [0.66666667, 0.43703704],
       [0.57142857, 0.28148148],
       [0.54761905, 0.53333333],
       [0.95238095, 0.05925926],
       [0.57142857, 0.36296296],
       [0.71428571, 0.13333333],
       [0.61904762, 0.91851852],
       [0.73809524, 0.0962963 ],
       [0.92857143, 0.13333333],
       [0.9047619 , 0.33333333],
       [0.73809524, 0.17777778],
       [0.5       , 0.41481481],
       [0.69047619, 0.14074074],
       [0.71428571, 0.14814815],
       [0.71428571, 0.13333333],
       [0.69047619, 0.05925926],
       [0.64285714, 0.22222222],
       [1.        , 0.2       ],
       [0.5       , 0.32592593],
       [0.66666667, 0.19259259],
       [0.78571429, 0.05925926],
       [0.76190476, 0.03703704],
       [0.42857143, 0.13333333],
       [0.73809524, 0.15555556]])

In [31]:
df

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [32]:
df = pd.get_dummies(df, columns=['Purchased'])
df

      User ID  Gender   Age  EstimatedSalary  Purchased_0  Purchased_1
0    15624510    Male  19.0          19000.0         True        False
1    15810944    Male  35.0          20000.0         True        False
2    15668575  Female  26.0          43000.0         True        False
3    15603246  Female  27.0          57000.0         True        False
4    15804002    Male  19.0          76000.0         True        False
..        ...     ...   ...              ...          ...          ...
395  15691863  Female  46.0          41000.0        False         True
396  15706071    Male  51.0          23000.0        False         True
397  15654296  Female  50.0          20000.0        False         True
398  15755018    Male  36.0          33000.0         True        False
399  15594041  Female  49.0          36000.0        False         True

[400 rows x 6 columns]

Data Integration

In [33]:
df_2 = pd.read_csv('Student_5.csv')
df_3 = pd.read_csv('student3.csv')

In [34]:
merged_data = pd.merge(df_2, df_3, on='roll')
merged_data

    roll   name_x class_x  marks _x  age_x   name_y class_y  marks _y  age_y
0      1     anil      TE     56.77   22.0     anil      TE     56.77   22.0
1      2     amit      TE     59.77   21.0     amit      TE     59.77   21.0
2      3   aniket      BE     76.88   19.0   aniket      BE     76.88   19.0
3      4  ajinkya      TE     69.66   20.0  ajinkya      TE     69.66   20.0
4      5     asha      TE     63.28    NaN     asha      TE     63.28    NaN
5      6   ayesha      BE       NaN   20.0   ayesha      BE       NaN   20.0
6      7     amar      BE     65.34   19.0     amar      BE     65.34   19.0
7      7     amar      BE     65.34   19.0     amar      BE     65.34   19.0
8      8    Amita      be    168.33   23.0    Amita      be     68.33   23.0
9      9     amol      TE     56.75   20.0     amol      TE     56.75   20.0
10     9     amol      TE     56.75   20.0     amol      TE     56.75   20.0
11    10    anmol      BE     78.66    NaN    anmol      BE     78.66    NaN
12    11   surbhi      TE       NaN   23.0   surbhi      TE       NaN   23.0
13    12    Sujay      TE     74.12   22.0    Sujay      TE     74.12   22.0
14    13  subhash      be     88.45  121.0  subhash      be     88.45   21.0
15    14   sachin     NaN     59.33   21.0   sachin     NaN     59.33   21.0
16    15  shalini      TE     63.45   20.0  shalini      TE     63.45   20.0